#!/bin/dash

# /etc/init.d/cache: an init script for all sorts of cache

case "$1" in
	start)
		# run nscd, the NSS cache daemon; it will cache DNS lookup results
		echo -n "Starting nscd ..."
		[ ! -d /run/nscd ] && mkdir /run/nscd
		nscd
		success=$?
		echo " done"
		[ 0 -ne $success ] && exit 1

		# update the cache of available image loaders - without this, GTK+ will
		# fail to load any images
		gdk_pixbuf_query_loaders="$(which gdk-pixbuf-query-loaders)"
		if [ -n "$gdk_pixbuf_query_loaders" ]
		then
			echo -n "Generating the GDK-PixBuf loaders cache ..."
			"$gdk_pixbuf_query_loaders" --update-cache
			success=$?
			echo " done"
			[ 0 -ne $success ] && exit 1
		fi

		# as of Pango 1.31.1, pango-querymodules supports "--update-cache", but
		# we want to support older versions, too - update the cache of available
		# modules; without this, text won't be rendered
		update_pango_querymodules="$(which update-pango-querymodules)"
		if [ -n "$update_pango_querymodules" ]
		then
			echo -n "Generating the Pango modules cache ..."
			"$update_pango_querymodules"
			success=$?
			echo " done"
			[ 0 -ne $success ] && exit 1
		fi

		exit 0
		;;

	stop)
		# stop nscd
		echo -n "Stopping nscd ..."
		nscd -K
		success=$?
		echo " done"
		exit $success
		;;

	restart)
		"$0" stop
		"$0" start
		;;

	*)
		echo "cache {start|stop|restart}"
		exit 1
		;;
esac
