#!/bin/dash

# /etc/init.d/cups: an init script for CUPS

case "$1" in
	start)
		echo -n "Starting CUPS ..."
		[ ! -d /run/cups ] && mkdir /run/cups
		cupsd
		success=$?
		pidof cupsd > /run/cups/cups.pid
		echo " done"
		exit $success
		;;

	stop)
		echo -n "Stopping CUPS ..."
		kill $(cat /run/cups/cups.pid)
		success=$?
		rm -f /run/cups/cups.pid
		echo " done"
		exit $success
		;;

	restart)
		"$0" stop
		"$0" start
		;;

	*)
		echo "cups {start|stop|restart}"
		exit 1
		;;
esac
