#!/bin/dash

# /etc/init.d/dropbear: a Dropbear init script

case "$1" in
	start)

		# generate the keys
		for i in rsa dss
		do
			[ -f /etc/dropbear/dropbear_${i}_host_key ] && continue
			echo -n "Generating dropbear_${i}_host_key ..."
			dropbearkey -t $i \
			            -f /etc/dropbear/dropbear_${i}_host_key > /dev/null 2>&1
			chown nobody:nobody /etc/dropbear/dropbear_${i}_host_key
			chmod 600 /etc/dropbear/dropbear_${i}_host_key
			echo " done"
		done

		echo -n "Starting Dropbear ..."

		# include the configuration file
		. /etc/init.conf.d/dropbear

		# create a directory for the pidfile
		pidfile_directory="$(dirname "$PIDFILE_PATH")"
		[ ! -d "$pidfile_directory" ] && mkdir "$pidfile_directory"
		chown nobody:nobody "$pidfile_directory"
		chmod 755 "$pidfile_directory"

		# start the server
		dropbear -P $PIDFILE_PATH $ADDITIONAL_OPTS
		echo " done"
		exit $?
		;;

	stop)
		echo -n "Stopping Dropbear ..."

		# include the configuration file
		. /etc/init.conf.d/dropbear

		# stop Dropbear
		kill $(cat "$PIDFILE_PATH")
		success=$?
		rm -f "$PIDFILE_PATH"

		echo " done"
		exit $success
		;;

	restart)
		"$0" stop
		"$0" start
		;;

	*)
		echo "dropbear {start|stop|restart}"
		exit 1
		;;
esac
