#!/bin/dash

# /etc/init.d/shared-mime-info: an init script for updating the database
#                               of known MIME types

[ "start" != "$1" ] && exit 0

# update the MIME database
if [ ! -f /usr/share/mime/mime.cache ]
then
	echo -n "Updating the MIME database ..."
	update-mime-database /usr/share/mime
	success=$?
	echo " done"
	[ 0 -ne $success ] && exit 1
fi

exit 0