#!/bin/dash

# /usr/bin/hpm-fetch: a package fetching and installation script, for single
#                     packages
# dependencies: DASH and roar-ng II

# the command-line usage message
USAGE="hpm-fetch NAME [distro version architecture]

Fetch and install a single package."

# include roar-ng's common functions file
. /usr/share/roar-ng/common

# check the command-line arguments
case $# in
	# if the distribution was not specified, pick the first distribution in the
	# distribution list
	1)
		distro="$(head -n 1 /$HPM_DISTRO_LIST_PATH)"
		;;

	# otherwise, use the specified distribution
	4)
		distro="$2 $3 $4"
		;;

	*)
		echo "$USAGE"
		exit 1
esac

# make sure the package is not installed already
if [ -e "/$PACKAGE_DATA_DIR/$1" ]
then
	echo "The package \"$1\" is already installed."
	exit 2
fi

# set the current distribution
set_current_distro $distro
if [ 0 -ne $? ]
then
	print_error "an invalid distribution was specified"
	exit 1
fi

# find the package entry
echo -n "Searching the package database ..."
package_entry="$(find_package $1)"
echo " done"

# if the package was not found, end here
if [ -z "$package_entry" ]
then
	print_error "could not find the \"$1\" package"
	exit 1
fi

# get the package file name
file_name="$(get_package_path "$package_entry")"
file_name="${file_name##*/}"

# create a temporary download path for the package
download_path="/$TMP_PREFIX/$file_name"
[ -e "$download_path" ] && download_path="$(mktemp -u)"

# download the package
download_package "$package_entry" "$download_path"

# install the package
hpm -i "$download_path" "$1" $distro
exit_code=$?

# delete the package
rm -f "$package_path"
[ 0 -ne $? ] && exit 1

exit 0