#!/bin/dash

# /usr/sbin/hpm-install: a package installer
# dependencies: dash, XZ Utils and roar-ng II

# the command-line usage message
USAGE="hpm-install PACKAGE NAME

Install a software package."

# check the command-line arguments
if [ 2 -ne $# ] || [ ! -f "$1" ] || [ -z "$2" ]
then
	echo "$USAGE"
	exit 1
fi

# include roar-ng's common functions file
. /usr/share/roar-ng/common

# make sure the package is not installed already
if [ -f "/$PACKAGE_DATA_DIR/$2" ]
then
	print_error "the package is already installed"
	exit 1
fi

# create a temporary directory for the package extraction
temp_dir="$(mktemp -d)"

# exctract the package to the temporary directory
echo -n "Extracting the package ..."
extract_tarball "$1" $temp_dir
if [ 0 -ne $? ]
then
	rm -rf $temp_dir
	print_error "failed to extract the package"
	exit 1
fi
echo " done"

# install the package files
echo -n "Installing files ..."
cp -rf $temp_dir/* /
if [ 0 -ne $? ]
then
	rm -rf $temp_dir
	print_error "failed to install the package files"
	exit 1
fi
echo " done"

# run the post-install script
if [ -f /$POST_INSTALL_SCRIPT_FILE_NAME ]
then
	execute_and_delete_script /$POST_INSTALL_SCRIPT_FILE_NAME
	[ 0 -ne $? ] && exit 1
fi

# register the installed package, so it can be removed using hpm-remove
echo -n "Registering the package ..."
register_package $temp_dir $2
echo " done"

rm -rf $temp_dir