#!/bin/dash

# /usr/sbin/hpm-remove: a package remover
# dependencies: dash

# the command-line usage message
USAGE="hpm-remove PACKAGE

Remove a software package."

# include roar-ng's common functions file
. /usr/share/roar-ng/common

# check the command-line arguments
if [ 1 -ne $# ] || [ ! -f "/$PACKAGE_DATA_DIR/$1" ]
then
	echo "$USAGE"
	exit 1
fi

success=1

# remove the package files
echo -n "Removing files ..."
for i in $(tac "/$PACKAGE_DATA_DIR/$1")
do
	if [ -f "$i" ]
	then
		rm -f "$i"
		if [ 0 -ne $? ]
		then
			success=0
			break
		fi
		continue
	fi

	if [ -d "$i" ]
	then
		rmdir "$i" 2>/dev/null
		continue
	fi
done

if [ 1 -ne $success ]
then
	print_error "failed to remove the package files"
	exit 1
fi
echo " done"

# run the post-removal script, if there is such
if [ -f "/$PACKAGE_DATA_DIR/$1-$POST_REMOVAL_SCRIPT_FILE_NAME" ]
then
	chmod +x "/$PACKAGE_DATA_DIR/$1-$POST_REMOVAL_SCRIPT_FILE_NAME"
	base_dir="$(pwd)"
	cd /
	"/$PACKAGE_DATA_DIR/$1-$POST_REMOVAL_SCRIPT_FILE_NAME"
	cd "$base_dir"
	rm -f "/$PACKAGE_DATA_DIR/$1-$POST_REMOVAL_SCRIPT_FILE_NAME"
fi

# unregister the package
echo -n "Unregistering the package ..."
rm -f "/$PACKAGE_DATA_DIR/$1"
if [ 0 -ne $? ]
then
	print_error "failed to unregister the package"
	exit 1
fi
echo " done"