#!/bin/dash

# /usr/bin/hpm-get: a package fetching and installation script, with recursive
#                   installation of dependencies
# dependencies: DASH and roar-ng II

# the command-line usage message
USAGE="hpm-get NAME [distro version architecture]

Fetch and install a package and its dependencies."

# include roar-ng's common functions file
. /usr/share/roar-ng/common

# check the command-line arguments
case $# in
	# if the distribution was not specified, pick the first distribution in the
	# distribution list
	1)
		distro="$(head -n 1 /$HPM_DISTRO_LIST_PATH)"
		;;

	# otherwise, use the specified distribution
	4)
		distro="$2 $3 $4"
		;;

	*)
		echo "$USAGE"
		exit 1
esac

# make sure the package is not installed already - if yes, it is assumed all
# dependencies are installed, too
if [ -e "/$PACKAGE_DATA_DIR/$1" ]
then
	echo "The package \"$1\" is already installed."
	exit 2
fi

# set the current distribution
set_current_distro $distro
if [ 0 -ne $? ]
then
	print_error "an invalid distribution was specified"
	exit 1
fi

# find the package entry
echo -n "Searching the package database for the dependencies of \"$1\" ..."
package_entry="$(find_package "$1")"
echo " done"

# if the package was not found, end here
if [ -z "$package_entry" ]
then
	print_error "could not find the \"$1\" package"
	exit 1
fi

# install all dependencies, in reversed order
for dependency in $(get_package_dependencies "$package_entry") "$1"
do
	# if there is recursive dependency, skip the package
	[ "$dependency" = "$1" ] && continue

	hpm-fetch "$dependency" $distro
	[ 1 -eq $? ] && exit 1
done

# install the package itself
hpm-fetch "$1" $distro
[ 1 -eq $? ] && exit 1

exit 0